# Generated by Django 5.0.3 on 2024-03-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(default='https://wallpapercave.com/wp/wp1813053.jpg'),
            preserve_default=False,
        ),
    ]
