# Generated by Django 5.0.3 on 2024-04-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='medicines',
            field=models.ManyToManyField(to='check.medicine'),
        ),
    ]
