# Generated by Django 5.0.3 on 2024-04-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_remove_cart_medicine_id_cart_medicines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='medicines',
            new_name='medicine_ids',
        ),
    ]
